language: python

python:
  - "3.5"

before_install:
  - sudo apt-get update -qq
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests and coverage
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage erase
  - coverage run -p manage.py test -v2

after_success:
  - coverage combine
  - coverage report
